"""
Django settings for TTS_server project.

Generated by 'django-admin startproject' using Django 5.2.1.

For more information on this file, see
https://docs.TTS_server.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.TTS_server.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.TTS_server.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-6pc)^&2_8h$wr8=lg6=2ezwkyq^hq%k6#_m^e4*o+5uce2c1vu"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# settings.py
ALLOWED_HOSTS = [
    '*'  # 개발환경에서는 모든 호스트 허용 (Docker 환경)
]

# Django의 호스트 검증 우회 (Docker 환경용)
USE_X_FORWARDED_HOST = True

# HTTP 통신 전용 설정

# HTTP 서버 URLs 설정 (Docker 네트워크 + 외부 통신)
# Docker 컨테이너 간 통신: 서비스 이름, 외부 호스트 통신: IP 주소
LLM_SERVER_URL = os.getenv('LLM_SERVER_URL', 'http://llm_server:5000')  # Docker 서비스 이름

# 외부 Java 컨트롤러 서버 URL 설정 (호스트 머신으로 전송)
EXTERNAL_SERVER_URL = os.getenv('EXTERNAL_SERVER_URL', 'http://10.0.10.99:8080/api/tts/receive')


# Application definition

INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "channels",  # Django Channels 추가 (WebSocket 지원)
    "ai"
]

# Channels 설정 (WebSocket 지원)
ASGI_APPLICATION = 'TTS_server.asgi.application'

# Channels Layer 설정 (메모리 기반 - 개발용)
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer'
    }
}

# WebSocket 로깅 설정
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'ai.consumers': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
        'daphne': {
            'handlers': ['console'],
            'level': 'DEBUG',
        },
    },
}

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # "django.middleware.common.CommonMiddleware",  # Docker 환경에서 호스트 검증 문제로 임시 비활성화
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "TTS_server.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / 'templates']
        ,
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "TTS_server.wsgi.application"

AUDIO_FILES_DIR = os.path.join(BASE_DIR, 'audio_files')


# Database
# https://docs.TTS_server.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.TTS_server.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.TTS_server.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.TTS_server.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Media files (음성 파일 저장용)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.TTS_server.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} {module} - {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} - {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'django.log',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },

        # 앱별 로거 (실제 앱 이름으로 변경)
        'ORAAISERVER': {  # 실제 앱 이름으로 변경하세요
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
        # 모든 로거 캐치
        '': {  # 루트 로거
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

